// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import AnimatedContainer from "@/components/AnimatedContainer/AnimatedContainer";
import CustomCursor from "@/components/CustomCursor/CustomCursor";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "my-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container m-auto w-screen h-screen overflow-hidden cursor-none relative`}
      >
        <Header />
        <AnimatedContainer>{children}</AnimatedContainer>
        <CustomCursor showIcon={null}/>
        <Footer />
      </body>
    </html>
  );
}
